### ISSUE TITLE
create section image

### ISSUE THREAD

**Issue by nguyendangnfq** [nguyendangnfq/fundraising-website#4]
![Screenshot from 2022-05-18 13-02-48](https://user-images.githubusercontent.com/104899842/168968318-3b9ab423-d8d6-4fac-bf4a-90f674350d16.png)

create on section ``<section class="parallax-ctn">`` and named: <strong>testimonial<strong>
create css named: testimonial.css

Demo: https://preview.themeforest.net/item/pifoxen-non-profit-charity-html-template/full_screen_preview/35212551?_ga=2.25203517.107702781.1652062980-757712034.1652062980

Thank you so much

**Comment by pum-nfq** [comment]
let me go!

**Comment by nguyendangnfq** [comment]
> let me go!

here you are !!! thank you
