### ISSUE TITLE
add resposive for section

### ISSUE THREAD

**Issue by nguyendangnfq** [nguyendangnfq/fundraising-website#6]
Please help me complementaring the responsive of <strong>testimonial section<strong>
Here the template: https://preview.themeforest.net/item/pifoxen-non-profit-charity-html-template/full_screen_preview/35212551?_ga=2.25203517.107702781.1652062980-757712034.1652062980

Thank you !!!

**Comment by pum-nfq** [comment]
let me!
Can u give me more info?
I need link of the design

**Comment by pum-nfq** [comment]
Hey @nguyendangnfq I'm finish this. Can you create branch for me push?

**Comment by nguyendangnfq** [comment]
https://github.com/nguyendangnfq/fundraising-website/tree/6-add-resposive-for-section
this is branch for you
