### ISSUE TITLE
section feature 

### ISSUE THREAD

**Issue by nguyendangnfq** [nguyendangnfq/fundraising-website#7]
![Screenshot from 2022-05-19 12-39-28](https://user-images.githubusercontent.com/104899842/169218508-57c31543-d393-4b9d-a513-f3408397f7f0.png)

section named: feature create on google map section. 
css file named: feature.css

link demo: https://preview.themeforest.net/item/pifoxen-non-profit-charity-html-template/full_screen_preview/35212551?_ga=2.25203517.107702781.1652062980-757712034.1652062980

**Comment by zevik7** [comment]
I will create a pull request soon

**Comment by nguyendangnfq** [comment]
> I will create a pull request soon

thank you, here you are !!!
